const path = require("path");
const fs = require("fs");
const DEVOS = require("../config");

function getFileContent(filePath) {
  try {
    const full = path.join(DEVOS.workspace, filePath);
    return fs.readFileSync(full, "utf-8");
  } catch {
    return null;
  }
}

function run(task, context, errors) {
  const target = context.topFiles?.[0] || { file: "/index.js" };
  const content = getFileContent(target.file);
  const lines = content ? content.split("\n") : [];

  const patchLines = [];
  if (lines.length > 0) {
    const contextLines = Math.min(3, lines.length);
    patchLines.push(`@@ -1,${contextLines} +1,${contextLines} @@`);
    for (let i = 0; i < contextLines; i++) {
      patchLines.push(" " + lines[i]);
    }
    patchLines.push(`+// AI patch for: ${task.slice(0, 60)}`);
  } else {
    patchLines.push(`@@ -0,0 +1,3 @@`);
    patchLines.push("+// Auto-generated by DevOS agent");
    patchLines.push(`+// Task: ${task.slice(0, 60)}`);
  }

  if (errors && errors.length > 0) {
    for (const e of errors.slice(0, 3)) {
      patchLines.push(`+// retry fix: ${e.error?.slice(0, 80)}`);
    }
  }

  return {
    title: `DevOS: ${task.slice(0, 80)}`,
    summary: `Auto-generated patch for task: ${task.slice(0, 120)}`,
    risk: "medium",
    files: [{
      path: target.file,
      patch: patchLines.join("\n"),
      reason: `Modified for task: ${task.slice(0, 100)}`,
    }],
  };
}

module.exports = { run };
