const { execSync } = require("child_process");
const path = require("path");
const fs = require("fs");
const DEVOS = require("../config");

function isAvailable() {
  try {
    execSync("Get-Command opencode", { shell: "powershell", stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function getGitDiff(workspaceRoot) {
  try {
    const diff = execSync("git diff", { cwd: workspaceRoot, encoding: "utf-8", stdio: "pipe" });
    const staged = execSync("git diff --cached", { cwd: workspaceRoot, encoding: "utf-8", stdio: "pipe" });
    const untrackedRaw = execSync("git ls-files --others --exclude-standard", { cwd: workspaceRoot, encoding: "utf-8", stdio: "pipe" });

    const combinedDiffs = [];
    let files = new Set();

    const diffText = [diff, staged].filter(Boolean).join("\n").trim();
    if (diffText) {
      combinedDiffs.push(diffText);
      const fileLines = diffText.split("\n").filter(l => l.startsWith("diff --git"));
      for (const line of fileLines) {
        const match = line.match(/diff --git a\/(.*?) b\//);
        if (match) files.add(match[1]);
      }
    }

    const untracked = untrackedRaw.trim().split("\n").filter(Boolean);
    for (const f of untracked) {
      const fullPath = path.join(workspaceRoot, f);
      if (fs.existsSync(fullPath)) {
        const content = fs.readFileSync(fullPath, "utf-8");
        combinedDiffs.push(`diff --git a/${f} b/${f}`);
        combinedDiffs.push("new file mode 100644");
        combinedDiffs.push("--- /dev/null");
        combinedDiffs.push(`+++ b/${f}`);
        const lines = content.split("\n");
        combinedDiffs.push(`@@ -0,0 +1,${lines.length} @@`);
        for (const l of lines) {
          combinedDiffs.push("+" + l);
        }
        files.add(f);
      }
    }

    if (files.size === 0) return null;

    return {
      diff: combinedDiffs.join("\n"),
      files: [...files],
    };
  } catch {
    return null;
  }
}

function buildPRFromDiff(task, gitResult) {
  if (!gitResult) return null;

  return {
    title: `DevOS (opencode): ${task.slice(0, 80)}`,
    summary: `Generated by opencode for task: ${task.slice(0, 120)}`,
    risk: "medium",
    files: gitResult.files.map(f => ({
      path: f,
      patch: gitResult.diff,
      _skipApply: true,
      reason: `Modified by opencode for: ${task.slice(0, 100)}`,
    })),
  };
}

function run(prompt, task) {
  if (!isAvailable()) {
    console.log("[OPENCODE] not found in PATH");
    return null;
  }

  const promptPath = path.join(DEVOS.logs, "ai_prompt.txt");
  fs.writeFileSync(promptPath, prompt, "utf-8");

  const workspaceRoot = DEVOS.workspace;

  console.log("[OPENCODE] Running opencode...");
  try {
    execSync(`Get-Content "${promptPath}" | opencode run --auto`, {
      cwd: workspaceRoot,
      encoding: "utf-8",
      maxBuffer: 50 * 1024 * 1024,
      timeout: 300000,
      shell: "powershell",
      stdio: "pipe",
    });
  } catch (e) {
    const stdout = e.stdout || "";
    const stderr = e.stderr || "";
    if (stdout) {
      const logPath = path.join(DEVOS.logs, "ai_output.txt");
      fs.writeFileSync(logPath, stdout, "utf-8");
    }
  }

  const gitResult = getGitDiff(workspaceRoot);
  if (gitResult) {
    console.log(`[OPENCODE] Modified ${gitResult.files.length} file(s)`);
    return buildPRFromDiff(task || "unknown", gitResult);
  }

  console.log("[OPENCODE] No changes detected");
  return null;
}

module.exports = { run, isAvailable };
